//images
import p1 from "../images/propertycard/p1.jpg";
import p2 from "../images/propertycard/p2.jpg";
import p3 from "../images/propertycard/p3.jpg";
import p4 from "../images/propertycard/p4.jpg";
import p5 from "../images/propertycard/p5.jpg";
import p6 from "../images/propertycard/p6.jpg";
import p7 from "../images/propertycard/p7.jpg";
import p8 from "../images/propertycard/p8.jpg";
import p9 from "../images/propertycard/p9.jpg";
import p10 from "../images/propertycard/p10.jpg";

const propertyCardInfo = [
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p1,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p2,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p3,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p4,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p5,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p6,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p7,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p8,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p9,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p10,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p2,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p7,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p6,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p9,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p2,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p1,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p2,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p4,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p8,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p1,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p10,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p6,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p1,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p2,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p4,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p8,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p1,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p8,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p9,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p10,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p2,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p7,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p6,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p9,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p2,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p1,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },

  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p4,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p8,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },

  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p2,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p4,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p8,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p1,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p8,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p9,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p10,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p2,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },

  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p2,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
  {
    actualPrice: 800000,
    discountedPrice: 750000,
    img: p9,
    bedhrooms: 3,
    bathrooms: 2,
    area: "12,386",
    mainHeading: "The Vanilla Park Homes",
    secHeading: "Ohio",
  },
];
console.log(propertyCardInfo.length);

export default propertyCardInfo;
